import { create } from 'zustand';

type Theme = 'light' | 'dark' | 'system';
type Locale = 'id' | 'en';

interface UiState {
	theme: Theme;
	locale: Locale;
	setTheme: (theme: Theme) => void;
	toggleTheme: () => void;
	setLocale: (locale: Locale) => void;
}

export const useUiStore = create<UiState>((set, get) => ({
	theme: 'system',
	locale: 'id',
	setTheme: (theme) => {
		set({ theme });
		applyTheme(theme);
	},
	toggleTheme: () => {
		const next = get().theme === 'dark' ? 'light' : 'dark';
		set({ theme: next });
		applyTheme(next);
	},
	setLocale: (locale) => set({ locale }),
}));

export function applyTheme(theme: Theme) {
	const root = document.documentElement;
	const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
	const shouldDark = theme === 'dark' || (theme === 'system' && prefersDark);
	root.classList.toggle('dark', shouldDark);
}

export const t = (key: string, params?: Record<string, any>) => {
	const dict = dictionaries[useUiStore.getState().locale] || {};
	let value = (dict as any)[key] || key;
	if (params) {
		Object.entries(params).forEach(([k, v]) => {
			value = value.replace(new RegExp(`{${k}}`, 'g'), String(v));
		});
	}
	return value;
};

const dictionaries: Record<Locale, Record<string, string>> = {
	id: {
		'app.title': 'Example POS by CodingGeh',
		'login.title': 'Masuk',
		'login.title': 'Masuk ke Sistem',
		'login.subtitle': 'Masuk dengan akun Anda untuk melanjutkan',
		'login.username': 'Username',
		'login.password': 'Kata Sandi',
		'login.placeholder.username': 'admin atau kasir',
		'login.placeholder.password': '••••••••',
		'login.submit': 'Masuk',
		'login.processing': 'Memproses...',
		'login.success': 'Selamat datang, {username}!',
		'login.error.emptyFields': 'Username dan password harus diisi',
		'login.error.invalid': 'Username atau password salah',
		'login.demo.title': 'Kredensial Demo',
		'nav.pos': 'POS',
		'nav.products': 'Produk',
		'nav.sales': 'Penjualan',
		'nav.dashboard': 'Dashboard',
		'nav.welcome': 'Selamat datang',
		'nav.logout': 'Keluar',
		'pos.title': 'Point of Sale',
		'pos.subtitle': 'Pilih produk untuk ditambahkan ke keranjang',
		'pos.error.loadProducts': 'Gagal memuat produk',
		'pos.error.outOfStock': 'Stok produk habis',
		'pos.error.emptyCart': 'Keranjang kosong',
		'pos.error.insufficientStock': 'Stock tidak mencukupi',
		'pos.error.discountNegative': 'Diskon tidak boleh negatif',
		'pos.error.discountExceedsTotal': 'Diskon tidak boleh melebihi total harga',
		'pos.error.transaction': 'Gagal memproses transaksi',
		'pos.addedToCart': 'ditambahkan ke keranjang',
		'pos.success.transaction': 'Transaksi berhasil!',
		'pos.cart.title': 'Keranjang',
		'pos.cart.items': 'item',
		'pos.cart.empty': 'Keranjang kosong',
		'pos.cart.subtotal': 'Subtotal',
		'pos.cart.discount': 'Diskon',
		'pos.cart.total': 'Total',
		'pos.cart.paymentMethod': 'Metode Pembayaran',
		'pos.cart.cash': 'Cash',
		'pos.cart.card': 'Card',
		'pos.cart.qris': 'QRIS',
		'pos.cart.notes': 'Catatan',
		'pos.cart.notesPlaceholder': 'Catatan transaksi...',
		'pos.cart.checkout': 'Checkout',
		'pos.cart.processing': 'Memproses...',
		'pos.cart.clear': 'Clear Cart',
		'sales.title': 'Riwayat Transaksi',
		'sales.subtitle': 'Lihat semua transaksi yang telah dilakukan',
		'sales.loading': 'Memuat...',
		'sales.empty': 'Belum ada transaksi',
		'sales.export': 'Ekspor CSV',
		'sales.exporting': 'Mengekspor...',
		'sales.search.placeholder': 'Cari transaksi...'	,
		'sales.pageSize': 'Baris per halaman',
		'sales.error.load': 'Gagal memuat transaksi',
		'sales.error.export': 'Gagal mengekspor data',
		'sales.error.emptyExport': 'Data ekspor kosong',
		'sales.success.export': 'Laporan penjualan berhasil diunduh',
		'sales.table.id': 'ID',
		'sales.table.date': 'Tanggal',
		'sales.table.total': 'Total',
		'sales.table.items': 'Item',
		'sales.pagination': 'Menampilkan {total} transaksi',
		'products.title': 'Manajemen Produk',
		'products.subtitle': 'Kelola produk dan stok',
		'products.loading': 'Memuat...',
		'products.empty': 'Belum ada produk',
		'products.add': 'Tambah Produk',
		'products.cancel': 'Batal',
		'products.save': 'Simpan',
		'products.edit': 'Edit',
		'products.delete': 'Hapus',
		'products.error.load': 'Gagal memuat produk',
		'products.error.save': 'Gagal menyimpan produk',
		'products.error.delete': 'Gagal menghapus produk',
		'products.success.create': 'Produk berhasil ditambahkan',
		'products.success.update': 'Produk berhasil diubah',
		'products.success.delete': 'Produk berhasil dihapus',
		'products.confirm.delete': 'Hapus produk ini?',
		'products.list.title': 'Daftar Produk',
		'products.table.name': 'Nama',
		'products.table.price': 'Harga',
		'products.table.stock': 'Stok',
		'products.table.actions': 'Aksi',
		'products.form.add': 'Tambah Produk',
		'products.form.edit': 'Edit Produk',
		'products.form.name': 'Nama Produk',
		'products.form.namePlaceholder': 'Masukkan nama produk',
		'products.form.description': 'Deskripsi',
		'products.form.descriptionPlaceholder': 'Masukkan deskripsi produk',
		'products.form.price': 'Harga',
		'products.form.stock': 'Stok',
		'notFound.title': 'Halaman Tidak Ditemukan',
		'notFound.subtitle': 'Periksa kembali URL atau kembali ke halaman utama',
		'common.currency': 'Rp',
		'common.quantity': '×',
		'common.separator': '—',
		'dashboard.title': 'Dashboard',
		'dashboard.subtitle': 'Ringkasan statistik toko',
		'dashboard.error.load': 'Gagal memuat data dashboard',
		'dashboard.stats.totalSales': 'Total Penjualan',
		'dashboard.stats.totalRevenue': 'Total Pendapatan',
		'dashboard.stats.totalProducts': 'Total Produk',
		'dashboard.stats.lowStock': 'Stok Menipis',
		'dashboard.charts.dailySales': 'Penjualan Harian',
		'dashboard.charts.topProducts': 'Produk Terlaris',
		'dashboard.charts.paymentMethods': 'Metode Pembayaran'
	},
	en: {
		'app.title': 'Example POS by CodingGeh',
		'login.title': 'Sign In',
		'login.title': 'Sign In to System',
		'login.subtitle': 'Sign in with your account to continue',
		'login.username': 'Username',
		'login.password': 'Password',
		'login.placeholder.username': 'admin or kasir',
		'login.placeholder.password': '••••••••',
		'login.submit': 'Sign In',
		'login.processing': 'Processing...',
		'login.success': 'Welcome, {username}!',
		'login.error.emptyFields': 'Username and password are required',
		'login.error.invalid': 'Invalid username or password',
		'login.demo.title': 'Demo Credentials',
		'nav.pos': 'POS',
		'nav.products': 'Products',
		'nav.sales': 'Sales',
		'nav.dashboard': 'Dashboard',
		'nav.welcome': 'Welcome',
		'nav.logout': 'Logout',
		'pos.title': 'Point of Sale',
		'pos.subtitle': 'Select products to add to cart',
		'pos.error.loadProducts': 'Failed to load products',
		'pos.error.outOfStock': 'Product out of stock',
		'pos.error.emptyCart': 'Cart is empty',
		'pos.error.insufficientStock': 'Insufficient stock',
		'pos.error.discountNegative': 'Discount cannot be negative',
		'pos.error.discountExceedsTotal': 'Discount cannot exceed total amount',
		'pos.error.transaction': 'Failed to process transaction',
		'pos.addedToCart': 'added to cart',
		'pos.success.transaction': 'Transaction successful!',
		'pos.cart.title': 'Cart',
		'pos.cart.items': 'items',
		'pos.cart.empty': 'Cart is empty',
		'pos.cart.subtotal': 'Subtotal',
		'pos.cart.discount': 'Discount',
		'pos.cart.total': 'Total',
		'pos.cart.paymentMethod': 'Payment Method',
		'pos.cart.cash': 'Cash',
		'pos.cart.card': 'Card',
		'pos.cart.qris': 'QRIS',
		'pos.cart.notes': 'Notes',
		'pos.cart.notesPlaceholder': 'Transaction notes...',
		'pos.cart.checkout': 'Checkout',
		'pos.cart.processing': 'Processing...',
		'pos.cart.clear': 'Clear Cart',
		'sales.title': 'Transaction History',
		'sales.subtitle': 'View all completed transactions',
		'sales.loading': 'Loading...',
		'sales.empty': 'No transactions yet',
		'sales.export': 'Export CSV',
		'sales.exporting': 'Exporting...',
		'sales.search.placeholder': 'Search transactions...'	,
		'sales.pageSize': 'Rows per page',
		'sales.error.load': 'Failed to load transactions',
		'sales.error.export': 'Failed to export data',
		'sales.error.emptyExport': 'Export data is empty',
		'sales.success.export': 'Sales report downloaded successfully',
		'sales.table.id': 'ID',
		'sales.table.date': 'Date',
		'sales.table.total': 'Total',
		'sales.table.items': 'Items',
		'sales.pagination': 'Showing {total} transactions',
		'products.title': 'Product Management',
		'products.subtitle': 'Manage products and stock',
		'products.loading': 'Loading...',
		'products.empty': 'No products yet',
		'products.add': 'Add Product',
		'products.cancel': 'Cancel',
		'products.save': 'Save',
		'products.edit': 'Edit',
		'products.delete': 'Delete',
		'products.error.load': 'Failed to load products',
		'products.error.save': 'Failed to save product',
		'products.error.delete': 'Failed to delete product',
		'products.success.create': 'Product added successfully',
		'products.success.update': 'Product updated successfully',
		'products.success.delete': 'Product deleted successfully',
		'products.confirm.delete': 'Delete this product?',
		'products.list.title': 'Product List',
		'products.table.name': 'Name',
		'products.table.price': 'Price',
		'products.table.stock': 'Stock',
		'products.table.actions': 'Actions',
		'products.form.add': 'Add Product',
		'products.form.edit': 'Edit Product',
		'products.form.name': 'Product Name',
		'products.form.namePlaceholder': 'Enter product name',
		'products.form.description': 'Description',
		'products.form.descriptionPlaceholder': 'Enter product description',
		'products.form.price': 'Price',
		'products.form.stock': 'Stock',
		'notFound.title': 'Page Not Found',
		'notFound.subtitle': 'Check the URL or return to the main page',
		'common.currency': 'Rp',
		'common.quantity': '×',
		'common.separator': '—',
		'dashboard.title': 'Dashboard',
		'dashboard.subtitle': 'Store statistics overview',
		'dashboard.error.load': 'Failed to load dashboard data',
		'dashboard.stats.totalSales': 'Total Sales',
		'dashboard.stats.totalRevenue': 'Total Revenue',
		'dashboard.stats.totalProducts': 'Total Products',
		'dashboard.stats.lowStock': 'Low Stock',
		'dashboard.charts.dailySales': 'Daily Sales',
		'dashboard.charts.topProducts': 'Top Products',
		'dashboard.charts.paymentMethods': 'Payment Methods'
	}
};


